[programs.localnet]
solana_anchor_escrow = "BgBM8rneuxRfido2bBwapiJYPVddQszTJhcjJkaHQV83"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/tomekregulski/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
